pub const DEFAULT_BASE_URL: &str = "https://verilib.org";

// CLI binary name - could also get this from env!("CARGO_PKG_NAME")
pub const CLI_NAME: &str = env!("CARGO_PKG_NAME");

// Dynamic error message generators
pub fn auth_required_msg() -> String {
    format!("No API key found. Please run '{} auth' first", CLI_NAME)
}

pub fn init_required_msg() -> String {
    format!("Project not initialized. Please run '{} init <repo_id>' first", CLI_NAME)
}

pub const DEFAULT_DOCKER_IMAGE: &str = "ghcr.io/beneficial-ai-foundation/verilib-cli:latest";

/// Common intermediate files generated by the atomize command.
pub const ATOMIZE_INTERMEDIATE_FILES: &[&str] = &["data/index.scip", "data/index.scip.json"];

/// Common intermediate files generated by the verify command.
pub const VERIFY_INTERMEDIATE_FILES: &[&str] =
    &["data/verification_config.json", "data/verification_output.txt"];

